name: Update commit hash
on:
  schedule:
    - cron: "0 0 1 * *" # Every 1st

jobs:
  change-commit:
    name: Change the commit hash to the latest upstream one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.name CI
          git config user.email ""
      - name: Update libevdev
        run: |
          latest_file=$(git ls-remote --sort=version:refname https://gitlab.freedesktop.org/libevdev/libevdev.git | awk -F/ 'END { print $NF }' | tr -d '^{}')
          evdev_url=https://www.freedesktop.org/software/libevdev
          sed -i "s|$evdev_url.*|$evdev_url/$latest_file.tar.xz|" org.duckstation.DuckStation.yml
          if ! git diff --exit-code --quiet; then
            sha256=$(wget -qO- $evdev_url/$latest_file.tar.xz | sha256sum - | awk '{print $1}')
            sed -i "/$latest_file/{n;s/sha256.*/sha256: $sha256/}" org.duckstation.DuckStation.yml
          fi
          git commit -am "Update libevdev" || exit 0
          git push
      - name: Update DuckStation
        run: |
          commit=$(git ls-remote https://github.com/stenzek/duckstation refs/tags/latest | cut -f 1)
          sed -i "/duckstation.git/{n;s/commit.*/commit: $commit/}" org.duckstation.DuckStation.yml
          git commit -am "Update duckstation.git" || exit 0
          git push
